[package]
name = "cpu-miner"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cpu-miner"
path = "src/main.rs"

[dependencies]
equihash = { version = "0.2", features = ["solver"] }
blake2b_simd = { workspace = true }
sha2 = "0.10"
serde_json = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
